import getpass
from io import StringIO
from time import perf_counter
USERNAME,CREATOR,HEX,FLAG,HEIGHT=getpass.getuser(),"Fiaguhop137",frozenset("0123456789abcdefABCDEF"),"flag",5040 
WIDTH,code,last_code,FILENAME=HEIGHT*4//3,"","","".join([FLAG,".svg"])
while True:
    try:
        text=input("Paste or type your code here: ").strip()
        code = "".join(c for c in text if c in HEX)
        t=perf_counter()
        if not code:continue
        if code!=last_code:    
            colors=[]
            for i in range(0,len(code)-5,6):
                color=code[i:i+6]
                if colors and colors[-1][0]==color:
                    colors[-1]=(color,colors[-1][1]+1)
                else:
                    colors.append((color,1))
            if not colors:continue
            total_stripes=len(code)//6
            with open(FILENAME,"w") as flag:
                svg = StringIO()
                svg.write(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" width="100%" height="100%">\n'f"<!-- Generated by {USERNAME} using {CREATOR}\'s flag generator -->\n")
                y=0
                last=len(colors)-1
                for index,(color,count) in enumerate(colors):
                    if index==last:    
                        height=HEIGHT-y
                    else:
                        height=count/total_stripes*HEIGHT
                    svg.write(f'<rect x="0" y="{y}" width="{WIDTH}" height="{height}" fill="#{color}"/>\n')
                    y+=height
                svg.write("</svg>\n")
                flag.write(svg.getvalue())
            last_code=code
        print(f"Flag generated in {(perf_counter()-t)*1000000:.2f} microseconds. You can find it at {FLAG}.svg.")
    except(EOFError,KeyboardInterrupt):
        print("\nBai~")
        break