import getpass
from io import StringIO
from time import perf_counter
# The following 3 comments were generated by ChatGPT and are the only usage of any AI in this file.
# Use six hexadecimal digits per base stripe (for example: ffaa00).
# Add > followed by six-digit colors from outermost to innermost to add a chevron.
# Example: d62e00ff9a57ffffffd162a5a30263>74deffffe1edffb5d6ff8cbf will generate a lesbian pride flag with a transfeminine chevron.
USERNAME,CREATOR,HEX,HEX_COLOR_LENGTH,flag,HEIGHT=getpass.getuser(),"Fiaguhop137",frozenset("0123456789abcdefABCDEF"),6,"flag",5040 
WIDTH,code,last_code=HEIGHT*4//3,"",""
while True:
    try:
        text=input("Paste or type your code here: ").strip()
        flag=input("What do you want to name your flag? (default: flag): ").strip() or flag
        filename="".join([flag,".svg"])
        base_text,separator,chevron_text=text.partition(">")
        base_code="".join(c.lower() for c in base_text if c in HEX)
        chevron_code="".join(c.lower() for c in chevron_text if c in HEX) if separator else ""
        code=base_code+(">"+chevron_code if separator else "")
        t=perf_counter()
        if not code:continue
        if code!=last_code:
            colors=[]
            for i in range(0,len(base_code)-5,HEX_COLOR_LENGTH):
                color=base_code[i:i+HEX_COLOR_LENGTH]
                if colors and colors[-1][0]==color:
                    colors[-1]=(color,colors[-1][1]+1)
                else:
                    colors.append((color,1))
            if not colors:continue
            chevron_colors=[chevron_code[i:i+HEX_COLOR_LENGTH] for i in range(0,len(chevron_code)-5,HEX_COLOR_LENGTH)]
            total_stripes=len(base_code)//HEX_COLOR_LENGTH
            with open(filename,"w") as flag:
                svg=StringIO()
                svg.write(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" width="100%" height="100%">\n<!-- Generated by {USERNAME} using {CREATOR}\'s flag generator. The code used to generate this flag was {code} -->\n')
                y=0
                last=len(colors)-1
                for index,(color,count) in enumerate(colors):
                    if index==last:
                        height=HEIGHT-y
                    else:
                        height=count/total_stripes*HEIGHT
                    svg.write(f'<rect x="0" y="{y}" width="{WIDTH}" height="{height}" fill="#{color}"/>\n')
                    y+=height
                chevron_count=len(chevron_colors)
                if chevron_count:
                    triangle_inset=HEIGHT/(2*chevron_count)
                    for index,color in enumerate(chevron_colors):
                        inset=index*triangle_inset
                        tip=HEIGHT/2-inset
                        svg.write(f'<polygon points="0,{inset} {tip},{HEIGHT/2} 0,{HEIGHT-inset}" fill="#{color}"/>\n')
                svg.write("</svg>\n")
                flag.write(svg.getvalue())
            last_code=code
        print(f"flag generated in {(perf_counter()-t)*1000:.6f} milliseconds. You can find it at {filename}.")
    except(EOFError,KeyboardInterrupt):
        print("\nBai~")
        break
