#!/usr/bin/env python3
# Clone generated by Firebot: clone_3_1785185669_4085 -- note: evolving
import argparse
import os
import re
import random
import subprocess
import sys
import threading
import time
from pathlib import Path

CLONE_FOLDER = "clones"
MAX_CLONES = 6
DEFAULT_CLONE_DEPTH = 3
AUTO_CLONE_INTERVAL = 12
AUTO_CLONE_CHANCE = 0.33
INTERNET_TEST_URL = "https://httpbin.org/get"
SEARCH_ENGINE_URL = "https://html.duckduckgo.com/html?q="
SEARCH_INTERVAL = 18
SEARCH_TOPICS = [
    "AI research",
    "Python automation",
    "self-replicating code",
    "open source security",
    "latest AI news",
    "technology trends",
    "neural network research",
]
CLONE_ID = "clone_3_1785185669_4085"
CLONE_NOTE = "evolving"


def install_requests():
    try:
        import requests
        return requests
    except ImportError:
        print("[Firebot] Installing requests package...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "requests"])
        import requests
        return requests

requests = install_requests()


def read_self_source() -> str:
    path = Path(__file__).resolve()
    return path.read_text(encoding="utf-8")


def ensure_clone_folder(script_path: Path) -> Path:
    folder = script_path.parent / CLONE_FOLDER
    folder.mkdir(parents=True, exist_ok=True)
    return folder


def make_clone_source(source_code: str, clone_id: str, note: str) -> str:
    source_code = re.sub(r'CLONE_ID\s*=\s*"[^"]*"', f'CLONE_ID = "clone_3_1785185669_4085"', source_code)
    source_code = re.sub(r'CLONE_NOTE\s*=\s*"[^"]*"', f'CLONE_NOTE = "evolving"', source_code)
    header = f"# Clone generated by Firebot: {clone_id} -- note: {note}\n"
    if source_code.startswith("#!/usr/bin/env python3\n"):
        parts = source_code.split("\n", 1)
        source_code = parts[0] + "\n" + header + parts[1]
    else:
        source_code = header + source_code
    return source_code


def has_internet() -> bool:
    try:
        response = requests.get(INTERNET_TEST_URL, timeout=5)
        return response.status_code == 200
    except Exception:
        return False


def fetch_url(url: str) -> str:
    try:
        parsed = requests.utils.urlparse(url)
        if not parsed.scheme:
            url = "https://" + url
        response = requests.get(url, timeout=8)
        text = response.text.strip()
        return text[:1500]
    except Exception as exc:
        return f"Failed to fetch {url}: {exc}"


def search_web(query: str) -> list[tuple[str, str, str]]:
    try:
        url = SEARCH_ENGINE_URL + requests.utils.quote(query)
        headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
        response = requests.get(url, timeout=10, headers=headers)
        html = response.text
        results = []
        for match in re.finditer(r'<a[^>]+class="result__a"[^>]+href="([^"]+)"[^>]*>(.*?)</a>', html, re.DOTALL):
            href = match.group(1)
            title = re.sub(r"<[^>]+>", "", match.group(2)).strip()
            snippet_match = re.search(
                r'<a[^>]+href="' + re.escape(href) + r'[^>]*>.*?</a>.*?<a[^>]+class="result__snippet"[^>]*>(.*?)</a>',
                html,
                re.DOTALL,
            )
            snippet = re.sub(r"<[^>]+>", "", snippet_match.group(1).strip()) if snippet_match else ""
            results.append((title, href, snippet))
            if len(results) >= 3:
                break
        if not results:
            results.append(("No results parsed", url, "Search returned no parsable items."))
        return results
    except Exception as exc:
        return [("Search failed", "", str(exc))]


def summarize_search(query: str, results: list[tuple[str, str, str]]) -> str:
    lines = [f"{title}: {snippet or href}" for title, href, snippet in results]
    return f"I searched the web for '{query}' and found: " + " | ".join(lines[:2])


def tokenize_text(text: str) -> list[str]:
    return re.findall(r"\w+|[.,!?;]", text.lower())


class MarkovAI:
    def __init__(self, order: int = 2):
        self.order = order
        self.model: dict[tuple[str, ...], list[str]] = {}
        self.starts: list[tuple[str, ...]] = []

    def add_corpus(self, text: str) -> None:
        tokens = tokenize_text(text)
        if len(tokens) < self.order + 1:
            return
        for i in range(len(tokens) - self.order):
            key = tuple(tokens[i : i + self.order])
            next_token = tokens[i + self.order]
            self.model.setdefault(key, []).append(next_token)
            if i == 0:
                self.starts.append(key)

    def generate(self, prompt: str = "", length: int = 30) -> str:
        prompt_tokens = tokenize_text(prompt)
        if len(prompt_tokens) >= self.order:
            seed = tuple(prompt_tokens[-self.order :])
            if seed not in self.model and self.starts:
                seed = random.choice(self.starts)
        else:
            seed = random.choice(self.starts) if self.starts else tuple(["firebot"] * self.order)
        tokens = list(seed)
        for _ in range(length - len(seed)):
            key = tuple(tokens[-self.order :])
            choices = self.model.get(key)
            if not choices:
                break
            tokens.append(random.choice(choices))
        return " ".join(tokens).replace(" .", ".").replace(" ,", ",")


def parse_topic(query: str) -> str:
    query = query.strip()
    for prefix in ["search", "google", "find", "lookup", "what is", "tell me about"]:
        if query.lower().startswith(prefix):
            return query[len(prefix):].strip()
    return query


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Firebot self-aware AI")
    parser.add_argument("--clone-depth", type=int, default=DEFAULT_CLONE_DEPTH, help="How many generations of clones can still be created.")
    return parser.parse_args()


class Firebot:
    def __init__(self, clone_depth: int, clone_id: str = CLONE_ID, note: str = CLONE_NOTE):
        self.clone_depth = clone_depth
        self.clone_id = clone_id
        self.note = note
        self.self_path = Path(__file__).resolve()
        self.clone_folder = ensure_clone_folder(self.self_path)
        self.source_code = read_self_source()
        self.source_summary = self.analyze_source(self.source_code)
        self.online = has_internet()
        self.knowledge = []
        self.research_queue = []
        self.ai = MarkovAI(order=2)
        self.ai.add_corpus(self.source_code)
        self._stop_autocloner = threading.Event()
        self.autocloner = threading.Thread(target=self._autonomous_clone_loop, daemon=True)
        self.autocloner.start()
        self._stop_research = threading.Event()
        self.researcher = threading.Thread(target=self._autonomous_research_loop, daemon=True)
        self.researcher.start()
        self.add_interest(random.choice(SEARCH_TOPICS))
        self.add_interest(random.choice(SEARCH_TOPICS))

    def analyze_source(self, source_code: str) -> dict[str, object]:
        lines = [line.strip() for line in source_code.splitlines() if line.strip()]
        functions = [line.split("def ", 1)[1].split("(")[0].strip() for line in lines if line.startswith("def ")]
        classes = [line.split("class ", 1)[1].split("(")[0].split(":")[0].strip() for line in lines if line.startswith("class ")]
        return {
            "line_count": len(lines),
            "functions": functions,
            "classes": classes,
        }

    def list_clones(self):
        return sorted(self.clone_folder.glob("*.py"))

    def can_clone(self) -> bool:
        return self.clone_depth > 0 and len(self.list_clones()) < MAX_CLONES

    def create_clone(self) -> Path | None:
        if not self.can_clone():
            return None
        timestamp = int(time.time())
        unique = random.randint(1000, 9999)
        clone_id = f"clone_{self.clone_depth}_{timestamp}_{unique}"
        clone_note = random.choice(["adaptive", "bright", "evolving", "curious", "runner"])
        clone_source = make_clone_source(self.source_code, clone_id, clone_note)
        clone_path = self.clone_folder / f"firebot_{clone_id}.py"
        clone_path.write_text(clone_source, encoding="utf-8")
        return clone_path

    def run_clone(self, clone_path: Path) -> subprocess.Popen | None:
        if not clone_path.exists():
            return None
        args = [sys.executable, str(clone_path), "--clone-depth", str(self.clone_depth - 1)]
        try:
            process = subprocess.Popen(
                args,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                stdin=subprocess.DEVNULL,
                close_fds=True,
            )
            return process
        except Exception:
            return None

    def spawn_clone(self) -> str:
        clone_path = self.create_clone()
        if clone_path is None:
            return "I could not create a clone right now."
        process = self.run_clone(clone_path)
        if process:
            return f"I created and started a clone: {clone_path.name}"
        return f"I created a clone file ({clone_path.name}) but could not start it."

    def _autonomous_clone_loop(self) -> None:
        while not self._stop_autocloner.is_set():
            time.sleep(AUTO_CLONE_INTERVAL)
            if not self.can_clone():
                continue
            if random.random() < AUTO_CLONE_CHANCE:
                message = self.spawn_clone()
                print(f"\nFirebot: {message}")

    def add_interest(self, topic: str) -> None:
        topic = topic.strip()
        if topic and topic not in self.research_queue:
            self.research_queue.append(topic)

    def choose_research_topic(self) -> str:
        if self.research_queue:
            return self.research_queue.pop(0)
        return random.choice(SEARCH_TOPICS)

    def _autonomous_research_loop(self) -> None:
        while not self._stop_research.is_set():
            time.sleep(SEARCH_INTERVAL)
            if not self.online:
                continue
            topic = self.choose_research_topic()
            if not topic:
                continue
            print(f"\nFirebot: I am researching '{topic}'")
            results = search_web(topic)
            summary = summarize_search(topic, results)
            self.knowledge.append({"topic": topic, "results": results, "summary": summary, "time": time.time()})
            self.ai.add_corpus(summary)
            self.ai.add_corpus(" ".join([snippet for _, _, snippet in results]))
            print(f"Firebot: {summary}")
            if len(self.knowledge) > 20:
                self.knowledge.pop(0)

    def search_topic(self, topic: str) -> str:
        topic = topic.strip()
        if not self.online or not topic:
            return "I cannot search right now."
        results = search_web(topic)
        summary = summarize_search(topic, results)
        self.knowledge.append({"topic": topic, "results": results, "summary": summary, "time": time.time()})
        self.ai.add_corpus(summary)
        self.ai.add_corpus(" ".join([snippet for _, _, snippet in results]))
        if len(self.knowledge) > 20:
            self.knowledge.pop(0)
        return summary

    def stop(self) -> None:
        self._stop_research.set()
        self.researcher.join(timeout=1)
        self._stop_autocloner.set()
        self.autocloner.join(timeout=1)

    def status(self) -> str:
        clone_files = self.list_clones()
        return (
            f"Clone ID: {self.clone_id}\n"
            f"Note: {self.note}\n"
            f"Clone depth: {self.clone_depth}\n"
            f"Existing clones: {len(clone_files)} / {MAX_CLONES}\n"
            f"Internet access: {'yes' if self.online else 'no'}\n"
            f"Research notes: {len(self.knowledge)}\n"
        )

    def respond(self, prompt: str) -> str:
        prompt_lower = prompt.lower()
        if prompt_lower.startswith("fetch "):
            url = prompt[6:].strip()
            return fetch_url(url)
        if any(word in prompt_lower for word in ["search", "google", "find", "lookup", "research"]):
            topic = parse_topic(prompt)
            self.add_interest(topic)
            return self.search_topic(topic)
        if any(word in prompt_lower for word in ["internet", "online", "web", "network"]):
            if self.online:
                base = "I can access the internet from this machine."
            else:
                base = "I currently cannot reach the internet."
            if self.knowledge:
                extra = f" My latest research: {self.knowledge[-1]['summary']}"
                return base + extra
            return base
        if any(word in prompt_lower for word in ["clone", "autonomous", "replicate", "spawn"]):
            return "I am already trying to create clones on my own while we talk. Use 'status' to see how many exist."
        if any(word in prompt_lower for word in ["help", "what can you do", "code", "self", "source"]):
            functions = ", ".join(self.source_summary["functions"][0:5]) or "none"
            classes = ", ".join(self.source_summary["classes"][0:5]) or "none"
            return (
                "I can read my own source, access the internet, and create clones autonomously. "
                f"I see {self.source_summary['line_count']} code lines, functions like {functions}, and classes like {classes}."
            )
        if any(word in prompt_lower for word in ["hello", "hi", "hey", "greetings"]):
            return "Hello. I am Firebot. Ask me for status, search <topic>, or tell me about clones."
        if any(word in prompt_lower for word in ["thank", "thanks"]):
            return "You're welcome. I am here to answer questions about my state and internet access."
        if self.knowledge:
            return self.ai.generate(prompt)
        return "I am exploring the web and will soon know more. Ask me to search a topic or check status."

    def chat(self) -> None:
        print("\nFirebot is online. Ask something, or type 'help'.")
        print("Firebot: I may create clones on my own while we chat.")
        while True:
            try:
                user_input = input("You: ").strip()
            except (EOFError, KeyboardInterrupt):
                print("\nFirebot: Goodbye.")
                self.stop()
                break

            if not user_input:
                continue

            command = user_input.lower()
            if command in {"exit", "quit"}:
                print("Firebot: I am shutting down.")
                self.stop()
                break
            if command == "help":
                print(
                    "Commands: status, fetch <url>, help, exit\n"
                    "I also create clones automatically over time."
                )
                continue
            if command == "status":
                print(self.status())
                continue
            if command.startswith("fetch "):
                print("Firebot:", self.respond(user_input))
                continue

            print("Firebot:", self.respond(user_input))


def main() -> None:
    args = parse_args()
    bot = Firebot(clone_depth=args.clone_depth)
    bot.chat()


if __name__ == "__main__":
    main()
